openapi: 3.0.0
info:
  title: JupyterLab FileSystem Server API
  version: 0.1.0

paths:
  /jupyterlab_filesystem/bucket/{bucketName}/{path}:
    get:
      summary: Get Bucket information at path
      parameters:
        - name: bucketName
          in: path
          required: true
          description: Bucket name
          schema:
            type: string
            format: uri
        - name: path
          in: path
          required: false
          description: Path
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: OK
        '404':
          description: Not found
        '403':
          description: Not authorized
